# Server settings
server.port=5000

# JPA and Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# JWT Configuration (Fallback defaults)
jwt.secret=${JWT_SECRET:super-secret-hospital-key}
jwt.expiration=86400000

# Groq API Configuration
groq.api.key=${GROQ_API_KEY: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}
